config/routes.rb
Rails.application.routes.draw do
  get 'rentals/new'
  get 'rentals/create'
  root to: 'pages#home'
  devise_for :users

  resource :profile, only: [:show, :update]

  #controllerS en tant que player
  resources :castles, only: [:index, :show] do
    resources :rentals, only: [:new, :create]
  end

  resources :rentals, only: [:index]

  # controller en tant que renter

  namespace :renter do
    resource :dashboard, only: [:show]
  #=> par defaut il n'y a qu'un seul dashboard par 'renter'
  #=> donc : singulier, pas d'index et pas d'id par dashboard
    resources :castles, only: [:new, :create]
    resources :rentals, only: [] do
      member do
        patch :accept
        patch :deny
      end
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/castle.rb
class Castle < ApplicationRecord
  mount_uploader :photo, PhotoUploader
  belongs_to :renter, class_name: 'User'
  has_many :rentals, dependent: :destroy
end

app/models/rental.rb
class Rental < ApplicationRecord
  belongs_to :castle
  belongs_to :player, class_name: 'User'
  before_save :default_values

  # validates :starts_on, presence: true
  # validates :ends_on, presence: true

  def default_values
    if self.status.nil?
      self.status = 'pending'
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  mount_uploader :avatar, AvatarUploader
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :castles, foreign_key: :renter_id
  has_many :rentals, foreign_key: :player_id

  # validates :email, presence: true, uniqueness: true => cf schema, inherited from devise
  validates :first_name, presence: true
  validates :last_name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  private

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name])

    # For additional in app/views/devise/registrations/edit.html.erb
    # devise_parameter_sanitizer.permit(:account_update, keys: [:username])
  end

  def after_sign_in_path_for(resource)
    castles_path
  end
end

app/controllers/castles_controller.rb
class CastlesController < ApplicationController
  skip_before_action :authenticate_user!, only: [:index, :show]
  before_action :set_castle, only: [:show]

  def index
    if params[:query].present?
      @castles = Castle.where("address ILIKE ?", "%#{params[:query]}%")
    else
      @castles = Castle.all
    end
  end

  def show
    @rental = Rental.new
  end

  private

  def set_castle
    @castle = Castle.find(params[:id])
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: :home

  def home
  end
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  def show
    @user = current_user
  end

  def update
    @user = current_user
    @user.update(user_params)
    redirect_to profile_path
  end

  private

  def user_params
    params.require(:user).permit(:avatar)
  end
end

app/controllers/rentals_controller.rb
class RentalsController < ApplicationController
  def index
    @rentals = current_user.rentals
  end

  def new
    @rental = Rental.new
    @castle = Castle.find(params[:castle_id])
  end

  def create
    @rental = Rental.new(rental_params)
    @rental.castle = Castle.find(params[:castle_id])
    @rental.player = current_user
    if @rental.save
      redirect_to rentals_path
    else
      render :new
    end
  end

  private

  def rental_params
    params.require(:rental).permit(:starts_on, :ends_on, :total_price)
  end
end

app/controllers/renter/castles_controller.rb
class Renter::CastlesController < ApplicationController
  def new
    @current_user = current_user
    @new_castle = Castle.new
  end
  
  def create
    @new_castle = Castle.new(new_castle_params)
    @new_castle.renter = current_user
    if @new_castle.save!
      redirect_to renter_dashboard_path
    else
      render :new
    end
  end

  private

  def new_castle_params
    params.require(:castle).permit(:name, :available, :nb_players, :description, :day_price, :address, :photo)
  end
end

app/controllers/renter/dashboards_controller.rb
class Renter::DashboardsController < ApplicationController
  def show
    # Let's anticipate on next week (with login)
    @current_user = current_user
    @castles = current_user.castles
  end
end

app/controllers/renter/rentals_controller.rb
class Renter::RentalsController < ApplicationController
  def accept
    @rental = Rental.find(params[:id])
    @rental.status = 'accepted'

    if @rental.save
      redirect_to renter_dashboard_path
    end
  end

  def deny
    @rental = Rental.find(params[:id])
    @rental.status = 'denied'

    if @rental.save
      redirect_to renter_dashboard_path
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/castles/index.html.erb
<div class="container">
  <div class="container text-center">
    <div class="page-intro m-3">
      <h1>BOUNCY CASTLES</h1>
      <% if @castles.empty? %>
          <h5 class="m-5">There's no castle yet in this city!!</h5>
      <% else %>
        <p>Start planning your party with these bouncing castles available</p>
      </div>
      <div class="row">
        <% @castles.each do |castle| %>
          <div class="col-sm-6 col-md-4">
              <%=  link_to castle_path(castle), class: 'card-index-link' do %>
                <div class="castle-index-card">
                    <div class="castle-index-img">
                      <%= cl_image_tag castle.photo, aspect_ratio: 1, crop: :fill %>
                      <div class="castle-index-players"><i class="fas fa-running"></i> <%= castle.nb_players %>
                      </div>
                    </div>
                    <div class="castle-index-card-body card-index-padding">
                      <h5 class="castle-index-card-title"><%= castle.name.upcase %></h5>
                      <i class="fas fa-map-marker-alt"></i> <%= castle.address %> | <%= castle.day_price %>€ <small>/day</small>
                    </div>
                </div>
              <% end %>
          </div>
        <% end %>
      <% end %>
    </div>
  </div>
</div>

app/views/castles/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm col-lg-8 offset-lg-2">
        <h2 class="mt-3 text-center"><%= @castle.name.upcase %></h2>
        <div class="castle-view">
          <div class="row align-items-stretch ">
              <div class="col-sm-12 col-md-6">
                <div class="castle-img">
                  <%= cl_image_tag @castle.photo, crop: :fill%>
                </div>
              </div>
              <div class="col-sm-12 col-md-6">
                <div class="castle-details">
                  <div class="castle-description">
                    <h5><%= @castle.description %></h5>
                  </div>
                  <div class="castle-players">
                    <i class="fas fa-running"></i> <strong><%= @castle.nb_players %> players</strong>
                  </div>
                  <div class="castle-price">
                    <i class="fas fa-euro-sign"></i> <%= @castle.day_price %> euros<small> per day</small>
                  </div>
                  <div class="castle-location">
                    <i class="fas fa-map-marker-alt"></i> <%= @castle.address %>
                  </div>
                </div>
                <div class="castle-owner-details">
                  <div class="notification-content">
                    <p>Meet the castle's owner</p>
                    <p><strong><%= @castle.renter.first_name %> <%= @castle.renter.last_name %></strong></p>
                    <p><small><i class="fas fa-info"></i> This person owns <%= @castle.renter.castles.count %> castle(s)</small></p>
                  </div>
                  <%= cl_image_tag @castle.renter.avatar, width: 150, crop: :fill, class: "avatar-large"%>
                </div>
              </div>
            </div>
        </div>
    </div>
  </div>
    <div class="row">
      <div class="col-sm-8 offset-sm-2 mb-3 text-center">
        <div class="form-basics">
        <h3>Ask to play with <%= @castle.name %></h3>
        <%= simple_form_for [@castle, @rental] do |f| %>
          <input type="text" id="rental-dates" placeholder="Select dates..." data-daily-price="<%= @castle.day_price %>" class='btn calendar-picker mt-2'>
          <%= f.input :total_price, as: :integer, required: false, input_html: {class: "d-none"}, label: false %>
          <%= f.input :starts_on, as: :string, required: false, input_html: {id: 'date_start', class: "d-none"}, label: false %>
          <%= f.input :ends_on, as: :string, required: false, input_html: {id: 'date_end', class: "d-none"}, label: false %>
          <div id="castle-total-price" class="mb-3"></div>
          <%= f.submit "Rent", class: "btn btn-warning btn-block" %>
        <% end %>
        </div>
      </div>
    </div>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Tigger's bounce</title>
    <%= favicon_link_tag "logo.png" %>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>
    <link href="https://fonts.googleapis.com/css?family=Lobster" rel="stylesheet">
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= stylesheet_pack_tag 'application', media: 'all' %> <!-- Uncomment if you import CSS in app/javascript/packs/application.js -->
  </head>
  <body>
    <%= render 'shared/navbar' unless controller_name == 'pages'%>
    <%#= render 'shared/flashes' %>
      <%= yield %>
    <%= javascript_include_tag 'application' %>
    <%= javascript_pack_tag 'application' %>
  </body>
</html>

app/views/pages/home.html.erb
<div class='wrapper'>
  <div class="banner d-flex align-items-center" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(<%= image_path "banner_2.png" %>);">
    <div class="container text-align">
      <div class="body-banner">
        <h1>TIGGER'S BOUNCE</h1>
        <p>Every cool party starts with a bounce</p>
        <%= link_to 'Find a castle', castles_path, class: 'btn btn-warning font-weight-bold' %>
      </div>
      <div class="connexion-bar">
        <% unless user_signed_in? %>
          <%= link_to "Log in", new_user_session_path, class: "btn"%>
          <%= link_to "Sign up", new_user_registration_path, class: "btn"%>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/profiles/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-8 offset-sm-2 mt-5 profile-card">
      <div class="profile-photo-avatar">
        <% if current_user.avatar.file.nil? %>
          <%= image_tag "default_avatar.png", width: 150, height: 150, class: "rounded-circle" %>
        <% else %>
          <%= cl_image_tag @user.avatar , width: 150, height: 150, crop: :fill, class: "rounded-circle" %>
        <% end %>
      </div>
      <div class="profile-details-text">
        <h1><%= @user.first_name + " " + @user.last_name %></h1>
        <h5><%= @user.email %></h5>
        <p>Member since: <%= @user.created_at.strftime("%d / %m / %Y") %></p>
        <%= simple_form_for @user, url: profile_path do |f| %>
          <%= f.input :avatar, label: false %>
          <%= f.input :avatar_cache, as: :hidden %>
          <%= f.submit "Change avatar", class: "btn btn-primary" %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/rentals/create.html.erb
<h1>Rentals#create</h1>
<p>Find me in app/views/rentals/create.html.erb</p>

app/views/rentals/index.html.erb
<div class="container">
  <div class="container text-center">
    <div class="page-intro m-3">
      <h1>MY ORDERS</h1>
    </div>
    <div class="row">
      <% @rentals.each do |rental| %>
      <div class="col-sm-6 col-md-4">
        <%=  link_to castle_path(rental.castle), class: 'card-index-link' do %>
          <div class="castle-index-card">
            <div class="castle-index-img">
              <%= cl_image_tag rental.castle.photo, width: 400, crop: :fill, class: 'card-img-top' %>
              <div class="castle-index-players"><i class="fas fa-running"></i> <%= rental.castle.nb_players %>
              </div>
            </div>
            <div class="castle-index-card-body pb-3">
              <h5 class="castle-index-card-title"><%= rental.castle.name.upcase %></h5>
                <div class="dates-badge"><strong><%= rental.starts_on.strftime("%d %B %Y") if rental.starts_on %>
                  <br>
                  <i class="fas fa-caret-right"></i> <%= rental.ends_on.strftime("%d %B %Y") if rental.ends_on %></strong></div>
                <% if rental.status == 'accepted' %>
                  <span class="text-success"><strong>order accepted</strong></span>
                <% elsif rental.status == 'denied'%>
                  <span class="text-danger"><strong>order denied</strong></span>
                <% else %>
                  <span><%= rental.status %></span>
                <% end %>
                <strong><%= rental.total_price %>€</strong>
                <br>
                <div class="owner-info"><small>Order sent to <%= rental.castle.renter.first_name %></small></div>
            </div>
          </div>
        <% end %>
      </div>
      <% end %>
    </div>
  </div>
</div>

app/views/renter/castles/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm form-basics">
      <h2 class="mt-3 text-center">My new bouncing castle</h2>
      <%= simple_form_for [:renter, @new_castle] do |f| %>
        <div class="form-row">
          <div class="col-sm-12 col-md-6">
            <%= f.input :name %>
          </div>
          <div class="col-sm-12 col-md-6">
            <%= f.input :photo %>
            <%= f.input :photo_cache, as: :hidden %>
          </div>
        </div>
        <div class="form-row">
          <div class="col-sm-12 col-md-4">
           <%= f.input :nb_players, collection: 1..100 %>
          </div>
          <div class="col-sm-12 col-md-4">
           <%= f.input :day_price %>
          </div>
          <div class="col-sm-12 col-md-4">
           <%= f.input :address %>
          </div>
        </div>
        <div class="form-row">
          <div class="col-sm-12">
            <%= f.input :description %>
          </div>
        </div>

        <%= f.submit "Add a Bouncing Castle!!!", class: "btn btn-primary" %>

      <% end %>
    </div>
  </div>
</div>

app/views/renter/dashboards/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm col-lg-8 offset-lg-2">
      <div class="dashboard">
        <h2 class="mt-3 text-center">MY CASTLES' DASHBOARD</h2>
        <h5 class="mt-3 text-center">MY CASTLES</h5>
        <div class="castles-list">
          <div class="row">
            <% @castles.each do |castle| %>
              <div class="col-md-6 my-1">
                 <div class="castle-renter-card d-flex justify-content-between align-items-center">
                   <%= castle.name %>
                   <div class="badge badge-primary badge-pill py-1 ml-1"><%= castle.rentals.count %></div>
                 </div>
              </div>
            <% end %>
            <div class="col-md-6 my-1">
              <%= link_to new_renter_castle_path, class: 'text-decoration-none' do %>
                <div class="castle-renter-card castle-add-btn">
                  <i class="fas fa-plus mr-2"></i> Add a castle
                </div>
              <% end %>
          </div>
          </div>
        </div>
        <h5 class="mt-3 text-center">ORDERS REVIEW</h5>
        <% @castles.each do |castle| %>
          <% castle.rentals.each do |rental| %>
            <div class="notification-dashboard">
              <%= cl_image_tag rental.player.avatar, width: 150, crop: :fill, class: "avatar-large"%>
              <div class="notification-content">
                <p><small>Request from <%= rental.player.first_name %> <%= rental.player.last_name %></small></p>
                <p><strong><%= rental.castle.name %></strong></p>
                <p>From <%= rental.starts_on.strftime("%d %B %Y") %> to <%= rental.ends_on.strftime("%d %B %Y") %></p>
                <p>For <%= rental.total_price %>€</p>
              </div>
              <div class="notification-status">
                <% if rental.status == 'accepted' %>
                  <span class="color-success">order accepted</span>
                <% elsif rental.status == 'denied'%>
                  <span class="color-deny">order denied</span>
                <% else %>
                  <span class="badge-infos"><%= rental.status %></span>
                <% end %>
              </div>
              <div class="notification-actions">
                <% if rental.status == 'pending' %>
                  <%= link_to accept_renter_rental_path(rental), method: :patch do %>
                    <i class="far fa-check-circle accept"></i>
                  <% end %>
                  <%= link_to deny_renter_rental_path(rental), method: :patch do %>
                    <i class="far fa-times-circle deny"></i>
                  <% end %>
                <% end %>
              </div>
            </div>
          <% end %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-primary">
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <%= link_to root_path, class: "navbar-brand" do %>
      <%= image_tag "logo.png", class: "rounded-circle" %>
    <% end %>
    <%= link_to 'All castles', castles_path, class: 'navbar-brand font-weight-bold ml-2' %>
      <form class="form-inline">
        <!-- <input class="form-control mr-sm-2" type="search" placeholder="ex: London..." aria-label="Search">
        <button class="btn btn-outline-light my-2 my-sm-0" type="submit">Search</button> -->
        <%= form_tag castles_path, method: :get do %>
          <%= text_field_tag :query,
            params[:query],
            class: "form-control",
            placeholder: "Search by city"
          %>
        <% end %>
      </form>

    <ul class="navbar-nav ml-auto">
      <% if user_signed_in? %>
        <li class="nav-item dropleft ml-auto">

          <% if current_user.avatar.file.nil? %>
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              <%= image_tag "default_avatar.png", width: 50, height:50, class: "rounded-circle" %>
            </a>
          <% else %>
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              <%= cl_image_tag current_user.avatar, width: 50, height:50, class: "rounded-circle navbar-avatar" %>
            </a>
          <% end %>

          <div class="dropdown-menu" aria-labelledby="navbarDropdown">
            <%= link_to "Dashboard", renter_dashboard_path, class: "dropdown-item" %>
            <%= link_to "My rental orders", rentals_path, class: "dropdown-item" %>
            <%= link_to "Profile", profile_path, class: "dropdown-item"%>
            <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
          </div>
        </li>
      <% else %>
        <li class="nav-item nav-right">
          <%= link_to user_session_path, class: "nav-link" do %>
            Log in
          <% end %>
        </li>
        <li class="nav-item nav-right">
          <%= link_to new_user_registration_path, class: "nav-link" do %>
            Sign up
          <% end %>
        </li>
      <% end %>
    </ul>
  </div>
</nav>